name: Update Webhook

on:
  workflow_run:
    workflows: ["Your Triggering Workflow"]  # Replace with the name of the workflow that triggers this update
    types:
      - completed

jobs:
  update_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install jq

      - name: Update Webhook
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}

          # Get the current webhook ID
          WEBHOOK_ID=$(curl -sH "Authorization: token $GITHUB_TOKEN" \
                        "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/hooks" \
                        | jq -r '.[] | select(.config.url == "http://20.51.210.213:30008/web-tt") | .id')

          if [ -z "$WEBHOOK_ID" ]; then
            echo "Webhook not found. Exiting."
            exit 1
          fi

          # Edit the existing webhook (replace with your desired settings)
          curl -sH "Authorization: token $GITHUB_TOKEN" \
               -X PATCH \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/hooks/$WEBHOOK_ID" \
               -d '{"config": {"url": "http://20.51.210.213:30008/web-tt", "content_type": "json"}}'
